name: pebl
description: "Pebl Habit Tracker - One pebble a day, A mountain someday."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl:

  # State Management
  provider: ^6.1.2

  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  uuid:

  # UI Components
  flutter_heatmap_calendar: ^1.0.5
  flutter_confetti:
  font_awesome_flutter:

  vibration:

  # Splash Screen
  flutter_native_splash: ^2.4.6

flutter_native_splash:
  color: "#262626"
  image: assets/pebl1.png
  android_gravity: center
  ios_content_mode: center
#
#  android_12:
#    color: "#262626"
#    image: assets/playstore.png
#    icon_background_color: "#262626"
#    branding: null



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # Code generation for Hive
  hive_generator: ^2.0.1
  build_runner: ^2.4.7

  # Launcher icon
  flutter_launcher_icons: "^0.14.4"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/playstore.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
